[package]
name = "rsjvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cesu8 = "1.1.0"
clippy = "0.0.302"
name-variant = "0.1.0"
rustfmt = "0.10.0"
thiserror = "1.0.60"
