on: [push]

name: Install Check Fmt Clippy

env: 
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  fmt-clippy:
    name: Fmt Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

        with:
          repository: defenestration1111111/.configs
          path: config-repo

      - name: Copy rustfmt.toml
        run: cp config-repo/rust/rustfmt.toml .
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Cargo fmt
        if: matrix.toolchain == 'nightly'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo clippy
        if: matrix.toolchain == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
