on: [push]

name: Install Check Fmt Clippy

env: 
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [class-reader, interpreter]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ${{ matrix.package }}/Cargo.toml

  lints:
    name: Fmt Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [class-reader, interpreter]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: defenestration1111111/.configs
          path: config-repo

      - name: Copy rustfmt.toml
        run: cp config-repo/rust/rustfmt.toml .

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ${{ matrix.package }}/Cargo.toml -- -D warnings

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ${{ matrix.package }}/Cargo.toml --all -- --check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [class-reader, interpreter]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: --manifest-path ${{ matrix.package }}/Cargo.toml
